/**
 * Таблица остатка неймспейса `mpu api` — 68 декларативных команд
 * (`docs/specs/api-write.md`). Одна строка — одна команда, как и у
 * читающей половины: сверх метода, пути и полей тела о команде знать
 * нечего.
 *
 * Методы, пути, поля и признаки сняты с объекта Python-реализации
 * (`docs/specs/fixtures/api/write-endpoints.json`); пояснения полей и
 * абзацы описаний — из машинного слепка дерева. Состав и снятые поля
 * стережёт `endpoints_write_test.ts`: расхождение с эталоном по имени,
 * методу, пути, параметрам, полям или признакам — красный тест.
 *
 * Одиннадцати кастомных команд остатка (`ss-access`, `wb-cards-reset`,
 * `api wb-loader-*`) здесь нет: у каждой своя механика, и таблицей они
 * не описываются.
 */

import type { EndpointSpec } from "./endpoint.ts";

export const WRITE_ENDPOINTS: readonly EndpointSpec[] = [
  {
    name: "add-client-ozon-key",
    method: "POST",
    path: "/admin/client/:clientId/ozon/apikey",
    fields: [
      {
        name: "seller_client_id",
        type: "string",
        help: "Ozon seller client_id",
      },
      { name: "seller_api_key", type: "string", help: "Ozon seller API key" },
      {
        name: "performance_client_id",
        type: "string",
        help: "performance API client_id",
      },
      {
        name: "performance_client_secret",
        type: "string",
        help: "performance API secret",
      },
      { name: "name", type: "string", help: "display name" },
    ],
    body: true,
    secretInput: true,
    sensitiveOutput: true,
  },
  {
    name: "add-client-wb-token",
    method: "POST",
    path: "/admin/client/:clientId/wb/token",
    fields: [
      { name: "token", type: "string", help: "WB JWT token" },
      { name: "description", type: "string", help: "free-text description" },
    ],
    secretInput: true,
    sensitiveOutput: true,
  },
  {
    name: "auth-change-password",
    method: "POST",
    path: "/auth/change-password",
    fields: [
      { name: "email", type: "string", help: "login email" },
      { name: "password", type: "string", help: "old password" },
      { name: "newPassword", type: "string", help: "new password" },
    ],
    secretInput: true,
  },
  {
    name: "auth-login",
    method: "POST",
    path: "/auth/login",
    fields: [
      { name: "email", type: "string", help: "login email" },
      { name: "password", type: "string", help: "password" },
    ],
    noAuth: true,
    secretInput: true,
    sensitiveOutput: true,
    about: "full response (accessToken + user)",
  },
  {
    name: "auth-logout",
    method: "POST",
    path: "/auth/logout",
  },
  {
    name: "auth-refresh",
    method: "GET",
    path: "/auth/refresh",
    sensitiveOutput: true,
    about: "refresh accessToken (admin only)",
  },
  {
    name: "auth-resend-email",
    method: "GET",
    path: "/auth/resendEmail",
  },
  {
    name: "auth-verify",
    method: "GET",
    path: "/auth/verify",
  },
  {
    name: "cli-log-heartbeat",
    method: "POST",
    path: "/admin/cli/log-heartbeat",
    fields: [
      { name: "key", type: "string", help: "log key" },
      { name: "level", type: "string", help: "log level" },
      { name: "cliRequestId", type: "string", help: "CLI request id" },
    ],
    secretInput: true,
  },
  {
    name: "cli-log-subscribe",
    method: "POST",
    path: "/admin/cli/log-subscribe",
    fields: [
      { name: "key", type: "string", help: "log key" },
      { name: "level", type: "string", help: "log level" },
      { name: "cliRequestId", type: "string", help: "CLI request id" },
    ],
    secretInput: true,
  },
  {
    name: "cli-log-unsubscribe",
    method: "POST",
    path: "/admin/cli/log-unsubscribe",
    fields: [
      { name: "key", type: "string", help: "log key" },
      { name: "cliRequestId", type: "string", help: "CLI request id" },
    ],
    secretInput: true,
  },
  {
    name: "cli-manifest",
    method: "POST",
    path: "/admin/cli/manifest",
    fields: [
      { name: "server", type: "string", help: "target server name" },
    ],
  },
  {
    name: "cli-run",
    method: "POST",
    path: "/admin/cli/run",
    fields: [
      { name: "server", type: "string", help: "target server name" },
      {
        name: "name",
        type: "string",
        help: "<type>:<name> dispatch (e.g. service:users)",
      },
      { name: "method", type: "string", help: "method to call" },
      { name: "args", type: "json", help: "args object as JSON" },
      { name: "requestId", type: "string", help: "optional request id" },
    ],
    body: true,
    about: "execute CLI on remote server",
  },
  {
    name: "cli-servers",
    method: "POST",
    path: "/admin/cli/servers",
    about: "list available servers",
  },
  {
    name: "create-client",
    method: "POST",
    path: "/admin/client",
    fields: [
      {
        name: "id",
        type: "number",
        help: "optional client_id (BIGSERIAL if omitted)",
      },
      { name: "title", type: "string", help: "display title" },
      { name: "is_active", type: "boolean", help: "is_active flag" },
    ],
    body: true,
  },
  {
    name: "create-client-spreadsheet",
    method: "POST",
    path: "/admin/client/:clientId/ss",
    fields: [
      { name: "spreadsheet_id", type: "string", help: "spreadsheet_id" },
      { name: "is_active", type: "boolean", help: "is_active flag" },
      { name: "script_id", type: "string", help: "Apps Script id" },
      { name: "title", type: "string", help: "display title" },
      { name: "template_name", type: "string", help: "template name" },
      { name: "subscriptionExpiresAt", type: "string", help: "ISO date" },
    ],
    body: true,
  },
  {
    name: "create-client-ss-dataset",
    method: "POST",
    path: "/admin/client/:clientId/ss/:spreadsheetId/dataset",
    fields: [
      { name: "dataset_name", type: "string", help: "dataset name" },
    ],
    body: true,
  },
  {
    name: "create-spreadsheet",
    method: "POST",
    path: "/admin/ss",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "spreadsheet_id", type: "string", help: "spreadsheet_id" },
      { name: "is_active", type: "boolean", help: "is_active flag" },
      { name: "script_id", type: "string", help: "Apps Script id" },
      { name: "title", type: "string", help: "display title" },
      { name: "template_name", type: "string", help: "template name" },
      { name: "subscriptionExpiresAt", type: "string", help: "ISO date" },
    ],
    body: true,
  },
  {
    name: "create-user",
    method: "POST",
    path: "/admin/user",
    fields: [
      { name: "email", type: "string", help: "user email" },
      { name: "password", type: "string", help: "password" },
      { name: "name", type: "string", help: "display name" },
      {
        name: "roles",
        type: "json",
        help: "roles array as JSON, e.g. '[\"admin\"]'",
      },
    ],
    body: true,
    secretInput: true,
    sensitiveOutput: true,
    about: "create user",
  },
  {
    name: "dataset-get",
    method: "POST",
    path: "/admin/client/:clientId/datasets/data/get",
    fields: [
      { name: "name", type: "string", help: "dataset name" },
      { name: "params", type: "json", help: "dataset params as JSON" },
    ],
    body: true,
  },
  {
    name: "dataset-save",
    method: "POST",
    path: "/admin/client/:clientId/datasets/data/save",
    fields: [
      { name: "name", type: "string", help: "dataset name" },
      { name: "params", type: "json", help: "dataset params as JSON" },
      { name: "data", type: "json", help: "rows as JSON" },
    ],
    body: true,
  },
  {
    name: "dataset-wb-unit-source",
    method: "POST",
    path: "/admin/client/:clientId/datasets/data/wb_unit_source",
    body: true,
  },
  {
    name: "delete-client",
    method: "DELETE",
    path: "/admin/client/:userId",
    about: "soft delete",
  },
  {
    name: "delete-client-ozon-key",
    method: "DELETE",
    path: "/admin/client/:clientId/ozon/apikey",
    fields: [
      {
        name: "seller_client_id",
        type: "string",
        help: "Ozon seller client_id",
      },
    ],
  },
  {
    name: "delete-client-spreadsheet",
    method: "DELETE",
    path: "/admin/client/:clientId/ss/:spreadsheetId",
  },
  {
    name: "delete-client-ss-dataset",
    method: "DELETE",
    path: "/admin/client/:clientId/ss/:spreadsheetId/dataset/:sheetName",
  },
  {
    name: "delete-client-wb-token",
    method: "DELETE",
    path: "/admin/client/:clientId/wb/token",
    fields: [
      { name: "token", type: "string", help: "WB JWT token to delete" },
    ],
    secretInput: true,
  },
  {
    name: "delete-spreadsheet",
    method: "DELETE",
    path: "/admin/ss/:spreadsheetId",
  },
  {
    name: "delete-user",
    method: "DELETE",
    path: "/admin/user/:userId",
    about: "soft delete",
  },
  {
    name: "destroy-client",
    method: "DELETE",
    path: "/admin/client/:userId/destroy",
    about: "HARD destroy (irreversible)",
  },
  {
    name: "dl-jobs-abort",
    method: "POST",
    path: "/admin/jobs/jobsControl/dataLoader/abort",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "dl-jobs-active-jobs",
    method: "POST",
    path: "/admin/jobs/jobsControl/dataLoader/active-jobs",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "dl-jobs-by-state",
    method: "POST",
    path: "/admin/jobs/jobsControl/dataLoader/jobs-by-state",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "dl-jobs-job",
    method: "POST",
    path: "/admin/jobs/jobsControl/dataLoader/job",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "dl-jobs-queue-status",
    method: "POST",
    path: "/admin/jobs/jobsControl/dataLoader/queue-status",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "dl-jobs-remove",
    method: "POST",
    path: "/admin/jobs/jobsControl/dataLoader/remove",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "integrity-findings",
    method: "POST",
    path: "/admin/integrity/findings",
    fields: [
      { name: "cursor", type: "json", help: "cursor object as JSON" },
      { name: "limit", type: "number", help: "page size" },
      { name: "sort", type: "string", help: "asc|desc" },
      { name: "status", type: "string", help: "open|resolved|all" },
      { name: "filter", type: "json", help: "filter object as JSON" },
    ],
    body: true,
    about: "(cursor-paginated)",
  },
  {
    name: "integrity-runs",
    method: "POST",
    path: "/admin/integrity/runs",
    fields: [
      { name: "cursor", type: "json", help: "cursor object as JSON" },
      { name: "limit", type: "number", help: "page size" },
      { name: "sort", type: "string", help: "asc|desc" },
      { name: "filter", type: "json", help: "filter object as JSON" },
    ],
    body: true,
    about: "(cursor-paginated)",
  },
  {
    name: "integrity-skips",
    method: "POST",
    path: "/admin/integrity/skips",
    fields: [
      { name: "cursor", type: "json", help: "cursor object as JSON" },
      { name: "limit", type: "number", help: "page size" },
      { name: "sort", type: "string", help: "asc|desc" },
      { name: "filter", type: "json", help: "filter object as JSON" },
    ],
    body: true,
    about: "(cursor-paginated)",
  },
  {
    name: "integrity-trigger",
    method: "POST",
    path: "/admin/integrity/trigger",
    about: "manually trigger check (support_lead+)",
  },
  {
    name: "ozon-jobs-abort",
    method: "POST",
    path: "/admin/jobs/jobsControl/ozon/abort",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ozon-jobs-active-jobs",
    method: "POST",
    path: "/admin/jobs/jobsControl/ozon/active-jobs",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ozon-jobs-by-state",
    method: "POST",
    path: "/admin/jobs/jobsControl/ozon/jobs-by-state",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ozon-jobs-job",
    method: "POST",
    path: "/admin/jobs/jobsControl/ozon/job",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ozon-jobs-queue-status",
    method: "POST",
    path: "/admin/jobs/jobsControl/ozon/queue-status",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ozon-jobs-remove",
    method: "POST",
    path: "/admin/jobs/jobsControl/ozon/remove",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ss-datasets-update",
    method: "POST",
    path: "/ss/datasets/update",
    fields: [
      {
        name: "spreadsheet_id",
        type: "string",
        help: "spreadsheet_id (Google Sheets)",
      },
      {
        name: "dataset",
        type: "json",
        help:
          'JSON {"name": "<datasetName>"} — обновить один датасет/лист; опустить — обновить всю таблицу (все активные датасеты)',
      },
    ],
    noAuth: true,
    about: "поставить запрос в очередь ss-updater (асинхронно)",
  },
  {
    name: "ss-jobs-abort",
    method: "POST",
    path: "/admin/jobs/ss/abort",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ss-jobs-active-jobs",
    method: "POST",
    path: "/admin/jobs/ss/active-jobs",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ss-jobs-by-state",
    method: "POST",
    path: "/admin/jobs/ss/jobs-by-state",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ss-jobs-job",
    method: "POST",
    path: "/admin/jobs/ss/job",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ss-jobs-queue-status",
    method: "POST",
    path: "/admin/jobs/ss/queue-status",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "ss-jobs-submit",
    method: "POST",
    path: "/admin/jobs/ss",
    fields: [
      {
        name: "type",
        type: "string",
        help: "тип job'а: accessGrantRevoke|accessGrantApply|...",
      },
      {
        name: "data",
        type: "json",
        help: 'данные job\'а, напр. {"grantId":"<uuid>"}',
      },
    ],
    body: true,
    about: "поставить любой ss-job {type, data}",
  },
  {
    name: "update-client",
    method: "PATCH",
    path: "/admin/client/:userId",
    fields: [
      { name: "is_active", type: "boolean", help: "is_active flag" },
      { name: "is_web", type: "boolean", help: "is_web flag" },
      { name: "title", type: "string", help: "display title" },
    ],
    body: true,
  },
  {
    name: "update-client-module",
    method: "PATCH",
    path: "/admin/client/:clientId/modules/:module",
    fields: [
      { name: "is_active", type: "boolean", help: "is_active flag" },
    ],
    about: "toggle is_active",
  },
  {
    name: "update-client-spreadsheet",
    method: "PATCH",
    path: "/admin/client/:clientId/ss/:spreadsheetId",
    fields: [
      { name: "is_active", type: "boolean", help: "is_active flag" },
      { name: "script_id", type: "string", help: "Apps Script id" },
      { name: "title", type: "string", help: "display title" },
      { name: "subscriptionExpiresAt", type: "string", help: "ISO date" },
    ],
    body: true,
  },
  {
    name: "update-client-ss-dataset",
    method: "PATCH",
    path: "/admin/client/:clientId/ss/:spreadsheetId/dataset/:sheetName",
    fields: [
      { name: "is_active", type: "boolean", help: "is_active flag" },
    ],
    body: true,
  },
  {
    name: "update-spreadsheet",
    method: "PATCH",
    path: "/admin/ss/:spreadsheetId",
    fields: [
      { name: "is_active", type: "boolean", help: "is_active flag" },
      { name: "script_id", type: "string", help: "Apps Script id" },
      { name: "title", type: "string", help: "display title" },
      { name: "subscriptionExpiresAt", type: "string", help: "ISO date" },
    ],
    body: true,
  },
  {
    name: "update-user",
    method: "PATCH",
    path: "/admin/user/:userId",
    fields: [
      { name: "email", type: "string", help: "user email" },
      { name: "password", type: "string", help: "new password" },
      { name: "name", type: "string", help: "display name" },
      { name: "is_active", type: "boolean", help: "is_active flag" },
      { name: "roles", type: "json", help: "roles array as JSON" },
    ],
    body: true,
    secretInput: true,
    sensitiveOutput: true,
  },
  {
    name: "update-wb-cabinet-module",
    method: "PATCH",
    path: "/admin/client/:clientId/wb-cabinets-modules/:sid/:module",
    fields: [
      { name: "is_active", type: "boolean", help: "is_active flag" },
    ],
    about: "toggle is_active",
  },
  {
    name: "wb-jobs-abort",
    method: "POST",
    path: "/admin/jobs/jobsControl/wb/abort",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "wb-jobs-active-jobs",
    method: "POST",
    path: "/admin/jobs/jobsControl/wb/active-jobs",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "wb-jobs-by-state",
    method: "POST",
    path: "/admin/jobs/jobsControl/wb/jobs-by-state",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "wb-jobs-job",
    method: "POST",
    path: "/admin/jobs/jobsControl/wb/job",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "wb-jobs-queue-status",
    method: "POST",
    path: "/admin/jobs/jobsControl/wb/queue-status",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "wb-jobs-remove",
    method: "POST",
    path: "/admin/jobs/jobsControl/wb/remove",
    fields: [
      { name: "client_id", type: "number", help: "client_id" },
      { name: "queue", type: "string", help: "BullMQ queue name" },
      {
        name: "state",
        type: "string",
        help: "active|waiting|completed|failed|delayed|paused",
      },
      { name: "jobId", type: "string", help: "BullMQ job id" },
      { name: "sid", type: "string", help: "(wb only) WB seller sid" },
      {
        name: "seller_client_id",
        type: "string",
        help: "(ozon only) seller client id",
      },
      { name: "limit", type: "number", help: "page size" },
    ],
    body: true,
  },
  {
    name: "wb-token-ping-content",
    method: "POST",
    path: "/admin/client/:clientId/wb/token/ping-content",
    fields: [
      { name: "token", type: "string", help: "WB JWT token" },
    ],
    secretInput: true,
    sensitiveOutput: true,
  },
  {
    name: "wb-token-seller-info",
    method: "POST",
    path: "/admin/client/:clientId/wb/token/seller-info",
    fields: [
      { name: "token", type: "string", help: "WB JWT token" },
    ],
    secretInput: true,
    sensitiveOutput: true,
  },
];
